/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentesRouteImport } from './routes/ventes'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AchatsRouteImport } from './routes/achats'
import { Route as IndexRouteImport } from './routes/index'

const VentesRoute = VentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AchatsRoute = AchatsRouteImport.update({
  id: '/achats',
  path: '/achats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/clients': typeof ClientsRoute
  '/ventes': typeof VentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/clients': typeof ClientsRoute
  '/ventes': typeof VentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/clients': typeof ClientsRoute
  '/ventes': typeof VentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/achats' | '/clients' | '/ventes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/achats' | '/clients' | '/ventes'
  id: '__root__' | '/' | '/achats' | '/clients' | '/ventes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchatsRoute: typeof AchatsRoute
  ClientsRoute: typeof ClientsRoute
  VentesRoute: typeof VentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventes': {
      id: '/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof VentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achats': {
      id: '/achats'
      path: '/achats'
      fullPath: '/achats'
      preLoaderRoute: typeof AchatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchatsRoute: AchatsRoute,
  ClientsRoute: ClientsRoute,
  VentesRoute: VentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
